server:
  port: 8010
  servlet:
    context-path: /credit-card-inventory

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5430/rba'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'none'
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: credit-card-inventory
      auto-offset-reset: earliest
      #disable retries on errors
      properties:
        max.poll.interval.ms: 300000
        retries: 0

cardCreation:
  api:
    base-url: http://localhost:8084/patient-last-activity-services  #https://api.something.com/v1
  timeout: 20000
